'use client';

import React from 'react';
import { AccordionSimple } from '../../components/UI/AccordionSimple';
import styles from './TermsConditionsContent.module.scss';

interface TermsSection {
  title: string;
  content: string;
}

const termsSections: TermsSection[] = [
  {
    title: "Scope; Order of Precedence",
    content: "These Terms form the base agreement between you and InstaReply. Additional documents may apply and are incorporated by reference, including our Privacy Policy, Acceptable Use (Section 13), Data Processing Addendum (DPA) when we process personal data on your behalf (Section 18), and any Order Form, SLA, or Enterprise Agreement we mutually execute.\n\nOrder of precedence (highest to lowest): (i) A signed Enterprise Agreement or Order Form (including any SLA addendum), (ii) DPA, (iii) these Terms, and (iv) documents referenced by link (e.g., Sub‑processor List). Conflicts are resolved by the higher-precedence document."
  },
  {
    title: "Eligibility; Business Use",
    content: "The Service is intended exclusively for business use. You must be at least 18 years old and authorized to bind your organization. You warrant that you are not subject to sanctions or residing in a jurisdiction where use of the Service would violate applicable law or export restrictions."
  },
  {
    title: "Definitions",
    content: "\"Account Data\" means Customer's admin/user profile information, billing details, configuration, and usage metrics that we process as Controller.\n\n\"Customer Content\" means content, data, messages, media, and prompts submitted to or generated by the Service for Customer's business purposes, processed by us as Processor.\n\n\"Seat\" means a license assigned to a named human user (admin, agent, or operator). Seats may not be shared.\n\n\"AI Agent Instance\" means a configured chatbot or workflow under your tenant.\n\n\"Usage Limits\" means plan-specific caps (e.g., unique conversations/month, channels, integrations, storage, API calls).\n\n\"Beta\" means pre‑release or experimental features provided \"as is\" for evaluation.\n\n\"Merchant of Record (Mor)\" means InstaReply or an authorized reseller/payment platform (e.g., a third‑party Mor) that bills you."
  },
  {
    title: "The Service",
    content: "Chat Agent is an AI‑powered messaging platform that helps businesses respond to and manage customer communications across supported channels (e.g., WhatsApp Business API, Instagram, Facebook Messenger, email/SMS gateways, web chat) and business systems (e.g., CRM/helpdesk), subject to these Terms and applicable third‑party rules.\n\nWe may update features, interfaces, and documentation from time to time. We will not materially reduce core functionality of a paid plan during a subscription term without providing substantially similar alternatives."
  },
  {
    title: "Free Trial; Beta Features",
    content: "Free trial: 30 days from activation, live from day one. Trial access may include usage limits, reduced support, or watermarks. We may end trials early for abuse or misuse.\n\nBeta: We may offer Beta features for testing. Beta is optional, may break, and may never be released. Beta is provided as is, excluded from any SLA, and may be subject to additional terms. You agree to provide feedback; we may use such feedback without restriction (Section 21)."
  },
  {
    title: "Onboarding Requirements (Go‑Live Controls)",
    content: "Before enabling \"Go Live\" production messaging, you must complete the final onboarding step and check both boxes in the product UI:\n\n1. AI limitations & non‑liability acknowledgment: you understand AI may produce incorrect or incomplete outputs and that you remain responsible for supervision and approval.\n\n2. Data verification acknowledgment: you have reviewed and approved all extracted/transcribed business data (e.g., menus, hours, services, policies).\n\nThese confirmations are technical gates and a condition precedent to production use. We may suspend Go‑Live if these acknowledgments are absent, withdrawn, or appear inaccurate."
  },
  {
    title: "Account Registration; Seats; Admins",
    content: "You must create an account and provide accurate information. You are responsible for safeguarding credentials, setting appropriate permissions/roles, and ensuring your team's compliance. Seats are for named users only and may not be shared or re‑assigned more than reasonable operationally (e.g., role change or departure)."
  },
  {
    title: "Plans, Limits, and Fair Use",
    content: "Plans are billed per Seat (per agent). Current plan highlights:\n\nStarter: up to 600 unique customer conversations/month; supports 2 languages; IG & WhatsApp auto‑reply.\n\nGrowth: up to 1,500 unique conversations/month; full multilingual; Instagram, WhatsApp & Facebook Messenger.\n\nPro: up to 3,000 unique conversations/month; full multilingual & dialect support; all major messaging platforms.\n\nEnterprise: starts at $999/Seat/month, 3,000+ conversations/month, unlimited platforms, integrations, and tailored pricing.\n\nAll plans include a 30‑day free trial. Annual billing: pay for 10 months, get 12. (Plan features/limits are summarized for convenience and may be refined in docs or an Order Form.)\n\nWe apply fair use protections (e.g., rate limits, storage caps, abuse prevention). If you exceed plan limits, we may (i) throttle usage, (ii) charge overages where agreed, or (iii) require plan upgrades. We will make reasonable efforts to notify you prior to material throttling, except for abuse or security concerns."
  },
  {
    title: "Payments, Taxes, and Refunds",
    content: "Fees: You agree to pay all fees for the selected plan and Seats. Fees are due in advance of each billing period and are exclusive of taxes.\n\nBilling entity / MoR: InstaReply or an authorized reseller/MoR may process billing, collections, and tax remittance. Your receipt or invoice will identify the MoR.\n\nTaxes: You are responsible for VAT/GST/sales and other applicable taxes. If withholding is required by law, you will gross‑up payments so we receive the full amount.\n\nRenewals: Monthly subscriptions renew month‑to‑month; annual subscriptions renew for successive 12‑month terms unless canceled as stated below.\n\nCancellations & refunds:\n\nYou may cancel at any time before renewal to avoid future charges.\n\nNo refunds for partial months or unused time/limits.\n\nEnterprise cancellations, early termination, and refunds are governed by the signed agreement or Order Form.\n\nPrice changes: We may adjust fees effective upon renewal with prior notice.\n\nLate payment & suspension: Overdue amounts may incur interest or collection costs. We may suspend or limit the Service for non‑payment after reasonable notice."
  },
  {
    title: "Acceptable Use and Prohibited Content",
    content: "You will not:\na) use the Service for illegal activities;\nb) violate third‑party platform terms (e.g., Meta/WhatsApp policies);\nc) send spam, deceptive, or harassing messages;\nd) attempt to bypass security, rate limits, or access controls;\ne) reverse engineer or copy the Service except as permitted by law;\nf) upload malware or interfere with others' use;\ng) use the Service to generate or disseminate content that is unlawful, hateful, or infringes intellectual property rights;\nh) submit Sensitive Data (e.g., health, government IDs, payment card data) unless explicitly permitted by a written agreement and implemented protections;\ni) use the Service for high‑risk advice (medical, legal, financial, or safety‑critical) without appropriate human review and disclaimers;\nj) engage in child exploitation or any content prohibited by law.\n\nWe may audit for compliance (e.g., via automated signals) and may remove, block, or suspend content or accounts for violations."
  },
  {
    title: "Third‑Party Platforms and Integrations",
    content: "If you enable integrations (e.g., WhatsApp Business API, Instagram, Facebook Messenger, email/SMS gateways, CRM/helpdesk), you authorize data exchange with those services and agree to their terms. We are not responsible for third‑party outages, policy changes, rate limits, messaging fees, or data handling by those services. Your credentials and API keys remain yours; you grant us permission to use them solely to operate the integration."
  },
  {
    title: "AI Transparency; Human Oversight",
    content: "AI can be wrong, incomplete, or out of date. You remain responsible for supervising AI outputs, configuring escalation and approval workflows, setting thresholds, and reviewing messages where accuracy matters. The Service is not a substitute for professional advice. Configure human‑in‑the‑loop for regulated or high‑risk use cases."
  },
  {
    title: "Intellectual Property; Feedback",
    content: "Except for the limited rights expressly granted, InstaReply retains all rights, title, and interest in the Service, including software, models, workflows, documentation, brand elements, and derivatives. The Service is licensed, not sold.\n\nIf you provide Feedback (suggestions, ideas, bug reports), you grant InstaReply a non‑exclusive, perpetual, irrevocable, royalty‑free license to use it without restriction.\n\nNo white‑label: The Service is not offered on a white‑label basis unless expressly agreed in writing."
  },
  {
    title: "Security; Incidents",
    content: "We implement administrative, technical, and physical safeguards designed to protect the Service and Customer Content. If we become aware of a personal data breach impacting Customer Content, we will notify you without undue delay and provide information required by law and our DPA.\n\nYou are responsible for endpoint security, secure credential management, and proper configuration of roles, retention, and integrations."
  },
  {
    title: "Data Protection; Roles; DPA",
    content: "For Customer Content, you are the Controller (or equivalent) and InstaReply is the Processor (or PDPL Data Manager). For Account Data, InstaReply is the Controller.\n\nIf you process personal data through the Service, our DPA applies and is incorporated into these Terms. The DPA sets out Processor obligations, sub‑processor conditions, security measures, assistance with data subject rights, international transfers (e.g., SCCs with UK addendum/IDTA), and audits.\n\nSub‑processors: We maintain a current list at [Insert Sub‑processor URL] and will provide notice of material changes as specified."
  },
  {
    title: "Service Levels and Support",
    content: "Standard support is included for paid plans during business hours (details in docs). Response times may vary by plan and severity.\n\nSLA (if purchased on Pro/Enterprise via Order Form):\n\nAvailability target: 99.9% monthly (excluding scheduled maintenance, force majeure, and outages attributable to third‑party platforms, ISPs, or your systems).\n\nCredits: 5% of monthly fees for availability <99.9% and ≥99.0%; 10% for <99.0% and ≥98.0%; 25% for <98.0%.\n\nExclusive remedy: Service credits are your sole remedy for SLA claims.\n\nProcess: Submit claims within 30 days of month‑end with logs/evidence.\n\nSLA does not apply to Free/Trial/Starter/Growth unless expressly stated on an Order Form."
  },
  {
    title: "Warranties and Disclaimers",
    content: "Mutual warranties: Each party warrants that it has the authority to enter these Terms and will comply with applicable laws in performing hereunder.\n\nService warranty disclaimer: EXCEPT AS EXPRESSLY PROVIDED, THE SERVICE AND BETA ARE PROVIDED \"AS IS\" AND \"AS AVAILABLE.\" INSTAREPLY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON‑INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE ERROR‑FREE, UNINTERRUPTED, OR MEET YOUR REQUIREMENTS, OR THAT AI OUTPUTS WILL BE ACCURATE OR COMPLETE."
  },
  {
    title: "Indemnification",
    content: "You will defend, indemnify, and hold InstaReply and its affiliates, officers, directors, employees, and agents harmless from and against any claims, damages, liabilities, costs, and expenses (including reasonable attorneys' fees) arising out of or related to: (a) your Customer Content; (b) your use of the Service in violation of these Terms or law; (c) your breach of third‑party platform terms; or (d) allegations that Customer Content infringes or misappropriates third‑party rights.\n\nWe will promptly notify you of any claim, allow you to control the defense/settlement (subject to our approval for settlements imposing obligations on us), and reasonably cooperate at your expense."
  },
  {
    title: "Limitation of Liability",
    content: "TO THE MAXIMUM EXTENT PERMITTED BY LAW:\na) IN NO EVENT WILL INSTAREPLY BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, OR FOR LOSS OF PROFITS, REVENUE, GOODWILL, OR DATA, EVEN IF ADVISED OF THE POSSIBILITY.\nb) INSTAREPLY'S TOTAL LIABILITY FOR ALL CLAIMS IN THE AGGREGATE SHALL NOT EXCEED THE AMOUNTS PAID OR PAYABLE BY YOU TO INSTAREPLY (OR THE MoR) FOR THE SERVICE IN THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO LIABILITY.\n\nSome jurisdictions do not allow certain limitations; in such cases, the limitations apply to the fullest extent permitted."
  },
  {
    title: "Suspension and Termination",
    content: "We may suspend or limit the Service immediately if: (i) you are in material breach (including non‑payment), (ii) security risk or suspected unlawful activity is detected, or (iii) required by law or third‑party platform policy.\n\nEither party may terminate for material breach not cured within 30 days after written notice. You may terminate at any time for convenience (no refunds for prepaid periods, except as stated in an Order Form). Upon termination: (a) your access ends; (b) fees due remain payable; and (c) upon request, we will delete or return Customer Content in accordance with our retention/backups schedule and the DPA."
  },
  {
    title: "Publicity; Marks",
    content: "We may identify your organization by name and logo as a customer in lists and case studies, subject to your right to opt out by written notice. Neither party will use the other's marks in a manner that suggests endorsement without prior written consent."
  },
  {
    title: "Export Controls; Sanctions; Anti‑Corruption",
    content: "You represent that you and your affiliates are not subject to sanctions and will not use the Service in violation of export control or sanctions laws. You will comply with anti‑bribery and anti‑corruption laws (e.g., UK Bribery Act, U.S. FCPA equivalents where applicable)."
  },
  {
    title: "Government Use",
    content: "The Service is commercial computer software. Government users obtain only those rights set forth in these Terms."
  },
  {
    title: "Assignment",
    content: "You may not assign or transfer these Terms without our prior written consent, except to a successor in connection with a merger, acquisition, or sale of substantially all assets, provided the assignee is not a competitor and assumes all obligations. We may assign to an affiliate or in connection with a corporate transaction."
  },
  {
    title: "Force Majeure",
    content: "Neither party is liable for failure or delay caused by events beyond reasonable control, including acts of God, natural disasters, war, terrorism, civil unrest, labor disputes, government actions, supply chain failure, utility/telecom outages, or third‑party platform failures."
  },
  {
    title: "Notices",
    content: "Notices to InstaReply must be in writing and sent to legal@instareply.io with a copy to our registered address in the Kingdom of Bahrain (see Privacy Policy). Notices to you may be sent to your account email or posted in the admin dashboard. Notices are deemed given on receipt or posting."
  },
  {
    title: "Modifications to Terms",
    content: "We may update these Terms to reflect operational, legal, or regulatory changes. Material changes take effect upon posting with notice via email or in‑product. If you continue using the Service after the effective date, you accept the updated Terms. If you object to material changes, you may terminate before they take effect."
  },
  {
    title: "Relationship of the Parties; No Third‑Party Beneficiaries",
    content: "The parties are independent contractors. These Terms create no partnership, agency, or employment relationship. There are no third‑party beneficiaries."
  },
  {
    title: "Severability; Waiver",
    content: "If any provision is found unenforceable, it will be enforced to the maximum extent permissible and the remainder will remain in effect. Failure to enforce any provision is not a waiver."
  },
  {
    title: "Entire Agreement",
    content: "These Terms, together with documents incorporated by reference and any applicable Order Form or Enterprise Agreement, constitute the entire agreement between the parties regarding the Service and supersede prior or contemporaneous understandings."
  },
  {
    title: "Governing Law; Venue",
    content: "These Terms are governed by the laws of the Kingdom of Bahrain, without regard to conflict‑of‑laws principles. Courts located in Manama, Bahrain shall have exclusive jurisdiction and venue for any disputes that are not subject to arbitration (if arbitration is agreed in an Enterprise Agreement). Each party consents to such jurisdiction and venue and waives any objection based on inconvenient forum."
  },
  {
    title: "Contact",
    content: "Legal: legal@instareply.io\nBilling: billing@instareply.io\nPrivacy: privacy@instareply.io"
  }
];

export const TermsConditionsContent: React.FC = () => {
  return (
    <div className={styles.termsConditionsContainer}>
      {/* Hero Section */}
      <div className={styles.heroSection}>
        <div className={styles.heroContent}>
          <h1 className={styles.heroTitle}>ChatAgent Terms & Conditions</h1>
          <p className={styles.heroSubtitle}>Updated September 14, 2025</p>
          
          <div className={styles.heroDescription}>
            <p>
              These Terms &amp; Conditions (&quot;Terms&quot;) govern your access to and use of Chat Agent and all related websites, dashboards, APIs, SDKs, plugins, and support channels (collectively referred to as the &quot;Service&quot;) provided by InstaReply W.L.L., a company based in the Kingdom of Bahrain (&quot;InstaReply,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;).
            </p>
          </div>

          {/* ChatAgent Icon */}
          <div className={styles.chatAgentIcon}>
            <svg width="76" height="75" viewBox="0 0 76 75" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M25.5066 23.8246C23.0033 23.8246 20.6523 24.7981 18.8907 26.5663C17.1291 28.3279 16.1556 30.6789 16.1556 33.1822C16.1556 35.6856 17.1291 38.0299 18.8907 39.7981C20.6523 41.5663 22.9901 42.5266 25.4801 42.5266C28.0033 42.5266 30.3477 41.5597 32.1159 39.7981C33.8841 38.0432 34.851 35.6922 34.851 33.1822C34.851 30.6723 33.8775 28.3346 32.1159 26.5663C30.3477 24.7981 27.9967 23.8246 25.5 23.8246H25.5066ZM30.2219 33.1822C30.2219 34.4405 29.7318 35.626 28.8377 36.5134C27.9437 37.4008 26.7583 37.8909 25.5066 37.8909C24.255 37.8909 23.0629 37.4008 22.1755 36.5134C21.2881 35.626 20.798 34.4405 20.7914 33.1756C20.7914 31.9173 21.2815 30.7319 22.1755 29.8379C23.0695 28.9438 24.255 28.4538 25.5066 28.4538C26.7583 28.4538 27.9503 28.9438 28.8377 29.8379C29.7318 30.7319 30.2219 31.924 30.2219 33.1756V33.1822ZM50.149 4.47363H25.8444C19.0762 4.47363 12.7053 7.10939 7.91722 11.8975C3.13576 16.6856 0.5 23.0498 0.5 29.818V36.5332C0.5 42.4935 2.61258 48.2882 6.4404 52.8445C9.78477 56.818 14.3477 59.712 19.3411 61.0299V67.0167C19.3411 67.9703 19.745 68.9173 20.4272 69.5531C21.0695 70.169 21.9305 70.52 22.8444 70.5266C23.4868 70.5266 24.1358 70.3412 24.6854 69.9968L38.6325 61.8776H50.1556C64.1291 61.8776 75.5 50.5067 75.5 36.5332V29.818C75.4934 15.8445 64.1225 4.47363 50.149 4.47363ZM50.149 57.2418H37.3675L37.2152 57.3346L23.9768 65.0432V57.2485L23.4338 57.1491L22.0762 56.8975C17.3675 56.0299 13.0762 53.5332 9.99007 49.8577C6.85762 46.1293 5.12914 41.3942 5.12914 36.5266V29.8114C5.12914 24.2882 7.28146 19.0895 11.1954 15.1756C15.1026 11.2683 20.3079 9.10939 25.8377 9.10277H50.1424C55.6722 9.10277 60.8709 11.2617 64.7848 15.1756C68.6921 19.0895 70.851 24.2882 70.851 29.8114V36.5266C70.851 42.0564 68.6987 47.2617 64.7848 51.1756C60.8709 55.0829 55.6656 57.2418 50.1424 57.2418H50.149ZM50.4868 23.8246C45.3278 23.8246 41.1291 28.0233 41.1291 33.1822C41.1291 35.6856 42.1026 38.0365 43.8709 39.7981C45.6325 41.5597 47.9768 42.5266 50.4868 42.5266C52.9967 42.5266 55.3344 41.5531 57.096 39.7915C58.8576 38.0365 59.8311 35.6856 59.8311 33.1822C59.8311 30.6789 58.8642 28.3346 57.1026 26.5663C55.3411 24.7981 52.9901 23.8246 50.4868 23.8246ZM55.1954 33.1822C55.1954 35.7783 53.0828 37.8909 50.4868 37.8909C49.2285 37.8909 48.0364 37.4008 47.1424 36.5134C46.255 35.626 45.7649 34.4405 45.7649 33.1822C45.7649 31.924 46.255 30.7385 47.149 29.8379C48.0364 28.9505 49.2219 28.4604 50.4868 28.4604C51.7517 28.4604 52.9238 28.9505 53.8245 29.8445C54.7119 30.7385 55.1954 31.924 55.1954 33.1822Z" fill="url(#paint0_linear_3356_15825)"/>
              <defs>
                <linearGradient id="paint0_linear_3356_15825" x1="-20.2897" y1="-34.6367" x2="93.2918" y2="-19.8509" gradientUnits="userSpaceOnUse">
                  <stop stopColor="#07A5EB"/>
                  <stop offset="1" stopColor="#3214F0"/>
                </linearGradient>
              </defs>
            </svg>
          </div>

          <div className={styles.heroSubDescription}>
            <p>
              By creating an account, starting a free trial, clicking to accept, or using the Service, you (&quot;Customer,&quot; &quot;you,&quot; or &quot;your&quot;) agree to these Terms. If you are accepting on behalf of an organization, you confirm that you have the authority to bind that organization. If you do not agree, please refrain from using the Service.
            </p>
          </div>
        </div>
      </div>

      {/* Terms & Conditions Accordion */}
      <div className={styles.accordionContainer}>
        <AccordionSimple items={termsSections} />
      </div>
    </div>
  );
};

export default TermsConditionsContent;
